kservices:
  - type: web
    name: blueprint-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: PORT
        value: 8000
